# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f5a562f52560bbe0eebe2d453995f20c0d7fb6332afdb8ef10e02839d6d091f2a072676beb9e1ed5852ac29811312310d60ddd886a1f351976cf88fef12faf3

test:
  secret_key_base: b1abf0942dc594857e64f058719bc1d5a3f28a546b84eae40cd01edb46d5fb63e7537bfdf936bc97a048943db1c120dbf4e94b12c1c53cc06797435dde2ff656

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
